### ISSUE TITLE
Ground Heat Flux

### ISSUE THREAD

**Issue by nmd1717** [FloEll/QWaterModel#7] opened 2022-01-11 19:26 UTC
When calculating the energy balance, the ground heat flux appears to not be calculated correctly. For example, I enter in "30" (to estimate heat flux as 30% of net radiation). Mean net radiation is 332 W/m2 but the ground heat flux reports as 0.45 W/m2. This appears regardless of what value I enter in for the ground heat flux or if I leave it blank. Any suggestions?

**Comment by FloEll** [comment] 2022-01-12 11:16
Hi, thanks for your message. I'm sorry to hear that you encountered a problem. Which version of QWaterModel are you using? I tried to replicate your problem using version 1.4 but it seems to work just fine. Then I also tested more extreme values (0%, 50% and 100%) and they all seem to be returning the expected percentage of ground heat flux. 
Could you maybe send me the version that you are currently using (QGIS and QWaterModel) and a data sample (e.g. to info@ecothermographylab.com) or post a link to your data here and I'll try to reproduce your observation.

**Comment by nmd1717** [comment] 2022-01-12 15:00
Thanks for the response. I am using version 1.4 with an older version of
QGIS (3.4.15) as I was having problems with 3.16. I will send a data sample
to the email address provided. Thank you!

**Comment by FloEll** [comment] 2022-02-07 10:24
I'm a bit late in posting this, but I think we found a solution here. Smaller sections of the data worked, however the whole map still produced the error described above. 
This could be either an issue with the map data or with the size of the map (if it is really, really large). However, we didn't really find out why the G-flux would show these patterns with this data. 

I'll close this issue now, because I think it is no longer relevant. 

Please re-open this issue again if you encounter similar difficulties.

**Closed as completed by FloEll** 2022-02-07 10:24 UTC
